language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

install:
    - "pip install -r requirements-build.txt"
    - "pip install --editable ."

script:
    - "pycodestyle"
    - "pytest tests/"

before_deploy:
    - "rst2html.py README.rst >docs/index.html"
    - "coverage-badge -f -o docs/coverage.svg"

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
        branch: master
        python: "3.6"

cache:
    apt: true
    pip: true
